######################################################################
#
# File name : gtwizard_0_TB_compile.do
# Created on: Mon Mar 11 22:12:59 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_auto_phase_align.v" \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_tx_startup_fsm.v" \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_rx_startup_fsm.v" \
"../ref/gtwizard/srcs/gtwizard_0_init.v" \
"../ref/gtwizard/srcs/gtwizard_0_gt.v" \
"../ref/gtwizard/srcs/gtwizard_0_multi_gt.v" \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_sync_block.v" \
"../ref/gtwizard/srcs/gtwizard_0.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_clock_module.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_common.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_common_reset.v" \
"../ref/gtwizard/imports/example_design/gtwizard_0_exdes.v" \
"../ref/gtwizard/imports/example_design/gtwizard_0_gt_frame_check.v" \
"../ref/gtwizard/imports/example_design/gtwizard_0_gt_frame_gen.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_gt_usrclk_source.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_support.v" \
"../ref/gtwizard/sim/gtwizard_0_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.gtwizard_0_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

view wave
view structure
view signals

run 1000ns
