######################################################################
#
# File name : gtwizard_0_TB_compile.do
# Created on: Mon Mar 11 22:12:59 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_auto_phase_align.v" \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_tx_startup_fsm.v" \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_rx_startup_fsm.v" \
"../ref/gtwizard/srcs/gtwizard_0_init.v" \
"../ref/gtwizard/srcs/gtwizard_0_gt.v" \
"../ref/gtwizard/srcs/gtwizard_0_multi_gt.v" \
"../ref/gtwizard/srcs/gtwizard_0/example_design/gtwizard_0_sync_block.v" \
"../ref/gtwizard/srcs/gtwizard_0.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_clock_module.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_common.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_common_reset.v" \
"../ref/gtwizard/imports/example_design/gtwizard_0_exdes.v" \
"../ref/gtwizard/imports/example_design/gtwizard_0_gt_frame_check.v" \
"../ref/gtwizard/imports/example_design/gtwizard_0_gt_frame_gen.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_gt_usrclk_source.v" \
"../ref/gtwizard/imports/example_design/support/gtwizard_0_support.v" \
"../ref/gtwizard/sim/gtwizard_0_tb.v" \


vlog -64 -incr -work work ../../baser/rtl/decode_64b_66b.v
vlog -64 -incr -work work ../../baser/rtl/descramble.v
vlog -64 -incr -work work ../../baser/rtl/encode_64b_66b.v
vlog -64 -incr -work work ../../baser/rtl/scramble.v
vlog -64 -incr -work work ../../baser/rtl/rx_alignment.v

vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../../gth_no_buffer_with_gearbox/rtl/axis2xgmii32.v
vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../../gth_no_buffer_with_gearbox/rtl/xgmii2axis32.v
vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../../gth_no_buffer_with_gearbox/rtl/rx.v
vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../../gth_no_buffer_with_gearbox/rtl/tx.v

vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../rtl/pcs_top.v
vlog -64 -incr -work work ../../gth_no_buffer_no_gearbox/rtl/gearbox_64b_66b.v
vlog -64 -incr -work work ../../gth_no_buffer_no_gearbox/rtl/gearbox_66b_64b.v
vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../rtl/prbs_gen.v
vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../rtl/prbs_check.v
vlog -64 -incr -work work +incdir+../../gth_no_buffer_with_gearbox/rtl ../rtl/prbs_test.v

vlog -64 -incr -work work ../../gth_no_buffer_with_gearbox/ref/gtwizard/imports/gtwizard_ultrascale_0_prbs_any.v

vlog -sv -64 -incr -work work ../../gth_no_buffer_with_gearbox/sim/sim_stream_master.sv
vlog -sv -64 -incr -work work ../../gth_no_buffer_with_gearbox/sim/tb_single_loopback.sv
vlog -sv -64 -incr -work work ./tb_prbs_loopback.sv

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib -lib work work.tb_prbs_loopback xil_defaultlib.glbl

do prbs_wave.do

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

view wave
view structure
view signals

run 1000ns
