######################################################################
#
# File name : gtwizard_ultrascale_0_example_top_sim_compile.do
# Created on: Mon Jan 21 11:05:07 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap work modelsim_lib/work

vlog -64 -incr -work xil_defaultlib  "+incdir+../ref/gtwizard/imports" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_v1_7_gthe3_channel.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gthe3_channel_wrapper.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_v1_7_gthe3_common.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gthe3_common_wrapper.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gtwizard_gthe3.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gtwizard_top.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_vio_0.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_bit_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_checking_64b66b.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_rx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_tx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_init.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_reset_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_stimulus_64b66b.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_wrapper.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_prbs_any.v" \

vlog -64 -incr -work work ../../baser/rtl/decode_64b_66b.v
vlog -64 -incr -work work ../../baser/rtl/descramble.v
vlog -64 -incr -work work ../../baser/rtl/encode_64b_66b.v
vlog -64 -incr -work work ../../baser/rtl/scramble.v
vlog -64 -incr -work work ../../baser/rtl/rx_alignment.v

vlog -64 -incr -work work +incdir+../rtl ../rtl/axis2xgmii32.v
vlog -64 -incr -work work +incdir+../rtl ../rtl/xgmii2axis32.v
vlog -64 -incr -work work +incdir+../rtl ../rtl/rx.v
vlog -64 -incr -work work +incdir+../rtl ../rtl/tx.v
vlog -64 -incr -work work +incdir+../rtl ../rtl/pcs_top.v

vlib modelsim_lib/msim/ten_gig_eth_mac_v15_1_5
vlib modelsim_lib/msim/gtwizard_ultrascale_v1_7_3
vlib modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_12
vlib modelsim_lib/msim/xlconstant_v1_1_4

vmap ten_gig_eth_mac_v15_1_5 modelsim_lib/msim/ten_gig_eth_mac_v15_1_5
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap gtwizard_ultrascale_v1_7_3 modelsim_lib/msim/gtwizard_ultrascale_v1_7_3
vmap ten_gig_eth_pcs_pma_v6_0_12 modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_12
vmap xlconstant_v1_1_4 modelsim_lib/msim/xlconstant_v1_1_4

vlog -64 -incr -work ten_gig_eth_mac_v15_1_5  \
"../../teng_ethernet/rtl/ipstatic/hdl/ten_gig_eth_mac_v15_1_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../teng_ethernet/rtl/bd/ip/ip_0/ten_gig_eth_mac_v15_1_1/hdl/bd_efdb_0_xmac_0_core.v" \
"../../teng_ethernet/rtl/bd/ip/ip_0/synth/bd_efdb_0_xmac_0_block.v" \
"../../teng_ethernet/rtl/bd/ip/ip_0/synth/bd_efdb_0_xmac_0.v" \

vlog -64 -incr -work gtwizard_ultrascale_v1_7_3  \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
"../../teng_ethernet/rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../teng_ethernet/rtl/bd/ip/ip_1/ip_0/sim/gtwizard_ultrascale_v1_7_gthe3_channel.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt_gthe3_channel_wrapper.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt_gtwizard_gthe3.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt_gtwizard_top.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt.v" \

vlog -64 -incr -work ten_gig_eth_pcs_pma_v6_0_12  \
"../../teng_ethernet/rtl/ipstatic/hdl/ten_gig_eth_pcs_pma_v6_0_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer_rst.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_local_clock_and_reset.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_sim_speedup_controller.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_cable_pull_logic.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_block.v" \
"../../teng_ethernet/rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0.v" \

vlog -64 -incr -work xlconstant_v1_1_4  \
"../../teng_ethernet/rtl/ipstatic/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../teng_ethernet/rtl/bd/ip/ip_2/sim/bd_efdb_0_dcm_locked_driver_0.v" \
"../../teng_ethernet/rtl/bd/ip/ip_3/sim/bd_efdb_0_pma_pmd_type_driver_0.v" \
"../../teng_ethernet/rtl/bd/sim/bd_efdb_0.v" \
"../../teng_ethernet/sim/axi_10g_ethernet_0.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_address_swap.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_axi_fifo.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_axi_mux.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_axi_pat_check.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_axi_pat_gen.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_clocking.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_ff_synchronizer_rst2.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_fifo_block.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_fifo_ram.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_gen_check_wrapper.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_gt_common.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_gt_common_wrapper.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_shared_clock_and_reset.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_shared_clocking_wrapper.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_support.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_sync_block.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_sync_reset.v" \
"../../teng_ethernet/rtl/imports/axi_10g_ethernet_0_xgmac_fifo.v" \
"../../teng_ethernet/rtl/imports/gtwizard_ultrascale_v1_7_gthe3_common.v" \

vlog -sv -64 -incr -work work ../sim/sim_stream_master.sv
vlog -64 -incr -work work ./axi_10g_ethernet_0_wrapper.v
vlog -sv -64 -incr -work work ./tb_system_across.sv

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

vsim -voptargs="+acc" -L ten_gig_eth_mac_v15_1_5 -L gtwizard_ultrascale_v1_7_3 -L ten_gig_eth_pcs_pma_v6_0_12 -L xlconstant_v1_1_4 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib -lib work work.tb_system_across xil_defaultlib.glbl

do wave.do
log -r *
run -all