######################################################################
#
# File name : axi_10g_ethernet_0_demo_tb_wave.do
# Created on: Tue Feb 12 20:09:59 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
