######################################################################
#
# File name : axi_10g_ethernet_0_demo_tb_simulate.do
# Created on: Tue Feb 12 20:09:59 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L ten_gig_eth_mac_v15_1_5 -L xil_defaultlib -L gtwizard_ultrascale_v1_7_3 -L ten_gig_eth_pcs_pma_v6_0_12 -L xlconstant_v1_1_4 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.axi_10g_ethernet_0_demo_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {axi_10g_ethernet_0_demo_tb_wave.do}

view wave
view structure
view signals

do {axi_10g_ethernet_0_demo_tb.udo}

run 1000ns
