######################################################################
#
# File name : axi_10g_ethernet_0_demo_tb_compile.do
# Created on: Tue Feb 12 20:09:47 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/ten_gig_eth_mac_v15_1_5
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/gtwizard_ultrascale_v1_7_3
vlib modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_12
vlib modelsim_lib/msim/xlconstant_v1_1_4

vmap ten_gig_eth_mac_v15_1_5 modelsim_lib/msim/ten_gig_eth_mac_v15_1_5
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap gtwizard_ultrascale_v1_7_3 modelsim_lib/msim/gtwizard_ultrascale_v1_7_3
vmap ten_gig_eth_pcs_pma_v6_0_12 modelsim_lib/msim/ten_gig_eth_pcs_pma_v6_0_12
vmap xlconstant_v1_1_4 modelsim_lib/msim/xlconstant_v1_1_4

vlog -64 -incr -work ten_gig_eth_mac_v15_1_5  \
"../rtl/ipstatic/hdl/ten_gig_eth_mac_v15_1_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../rtl/bd/ip/ip_0/ten_gig_eth_mac_v15_1_1/hdl/bd_efdb_0_xmac_0_core.v" \
"../rtl/bd/ip/ip_0/synth/bd_efdb_0_xmac_0_block.v" \
"../rtl/bd/ip/ip_0/synth/bd_efdb_0_xmac_0.v" \

vlog -64 -incr -work gtwizard_ultrascale_v1_7_3  \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
"../rtl/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \

vlog -64 -incr -work xil_defaultlib  \
"../rtl/bd/ip/ip_1/ip_0/sim/gtwizard_ultrascale_v1_7_gthe3_channel.v" \
"../rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt_gthe3_channel_wrapper.v" \
"../rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt_gtwizard_gthe3.v" \
"../rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt_gtwizard_top.v" \
"../rtl/bd/ip/ip_1/ip_0/sim/bd_efdb_0_xpcs_0_gt.v" \

vlog -64 -incr -work ten_gig_eth_pcs_pma_v6_0_12  \
"../rtl/ipstatic/hdl/ten_gig_eth_pcs_pma_v6_0_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer_rst.v" \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_ff_synchronizer.v" \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_local_clock_and_reset.v" \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_sim_speedup_controller.v" \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_cable_pull_logic.v" \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0_block.v" \
"../rtl/bd/ip/ip_1/synth/bd_efdb_0_xpcs_0.v" \

vlog -64 -incr -work xlconstant_v1_1_4  \
"../rtl/ipstatic/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../rtl/bd/ip/ip_2/sim/bd_efdb_0_dcm_locked_driver_0.v" \
"../rtl/bd/ip/ip_3/sim/bd_efdb_0_pma_pmd_type_driver_0.v" \
"../rtl/bd/sim/bd_efdb_0.v" \
"./axi_10g_ethernet_0.v" \
"../rtl/imports/axi_10g_ethernet_0_address_swap.v" \
"../rtl/imports/axi_10g_ethernet_0_axi_fifo.v" \
"../rtl/imports/axi_10g_ethernet_0_axi_mux.v" \
"../rtl/imports/axi_10g_ethernet_0_axi_pat_check.v" \
"../rtl/imports/axi_10g_ethernet_0_axi_pat_gen.v" \
"../rtl/imports/axi_10g_ethernet_0_clocking.v" \
"../rtl/imports/axi_10g_ethernet_0_example_design.v" \
"../rtl/imports/axi_10g_ethernet_0_ff_synchronizer_rst2.v" \
"../rtl/imports/axi_10g_ethernet_0_fifo_block.v" \
"../rtl/imports/axi_10g_ethernet_0_fifo_ram.v" \
"../rtl/imports/axi_10g_ethernet_0_gen_check_wrapper.v" \
"../rtl/imports/axi_10g_ethernet_0_gt_common.v" \
"../rtl/imports/axi_10g_ethernet_0_gt_common_wrapper.v" \
"../rtl/imports/axi_10g_ethernet_0_shared_clock_and_reset.v" \
"../rtl/imports/axi_10g_ethernet_0_shared_clocking_wrapper.v" \
"../rtl/imports/axi_10g_ethernet_0_support.v" \
"../rtl/imports/axi_10g_ethernet_0_sync_block.v" \
"../rtl/imports/axi_10g_ethernet_0_sync_reset.v" \
"../rtl/imports/axi_10g_ethernet_0_xgmac_fifo.v" \
"../rtl/imports/gtwizard_ultrascale_v1_7_gthe3_common.v" \
"../rtl/imports/axi_10g_ethernet_0_demo_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"


