######################################################################
#
# File name : ten_gig_eth_mac_0_demo_tb_compile.do
# Created on: Tue Jan 22 11:40:25 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work

vmap work work

vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/axis2xgmii.v
vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/nfmac10g.v
vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/padding_ctrl.v
vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/rst_mod.v
vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/rx.v
vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/tx.v
vlog -64 -incr -work work +incdir+../src/hdl ../src/hdl/xgmii2axis.v

vlog -64 -incr -sv -work work ../../../sim/sim_stream_master.sv
vlog -64 -incr -sv -work work ./top.sv
# compile glbl module
vlog -work work "glbl.v"

vsim -voptargs="+acc" -L work -lib work work.top work.glbl

log -r *
run 10us