######################################################################
#
# File name : gtwizard_0_example_top_sim_compile.do
# Created on: Fri Aug 31 10:22:59 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/gtwizard_ultrascale_v1_6_3
vlib msim/xil_defaultlib

vmap gtwizard_ultrascale_v1_6_3 msim/gtwizard_ultrascale_v1_6_3
vmap xil_defaultlib msim/xil_defaultlib

vlog -work xil_defaultlib ../rtl/decode_64b_66b.v
vlog -work xil_defaultlib ../rtl/encode_64b_66b.v
vlog -work xil_defaultlib ../rtl/descramble.v
vlog -work xil_defaultlib ../rtl/scramble.v
vlog -work xil_defaultlib ../rtl/rx_alignment.v
vlog -work xil_defaultlib ../rtl/pcs_top.v

vlog -work xil_defaultlib -sv ./tb_single_loopback.sv


vlog -64 -incr -work gtwizard_ultrascale_v1_6_3  "+incdir+../ref/gtwizard/ipstatic" "+incdir+../ref/gtwizard/sim" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_bit_synchronizer.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gthe3_cpll_cal.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gthe3_cpll_cal_freq_counter.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gthe4_cpll_cal.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gthe4_cpll_cal_freq_counter.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtye4_cpll_cal.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtye4_cpll_cal_freq_counter.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_rx.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_tx.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_reset.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_userclk_rx.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_userclk_tx.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_userdata_rx.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_gtwiz_userdata_tx.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_reset_synchronizer.v" \
"../ref/gtwizard/ipstatic/gtwizard_ultrascale_v1_6_reset_inv_synchronizer.v" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../ref/gtwizard/ipstatic" "+incdir+../ref/gtwizard/sim" \
"../ref/gtwizard/sim/gtwizard_ultrascale_v1_6_gthe3_channel.v" \
"../ref/gtwizard/sim/gtwizard_0_gthe3_channel_wrapper.v" \
"../ref/gtwizard/sim/gtwizard_ultrascale_v1_6_gthe3_common.v" \
"../ref/gtwizard/sim/gtwizard_0_gthe3_common_wrapper.v" \
"../ref/gtwizard/sim/gtwizard_0_gtwizard_gthe3.v" \
"../ref/gtwizard/sim/gtwizard_0_gtwizard_top.v" \
"../ref/gtwizard/sim/gtwizard_0.v" \
"../ref/gtwizard/sim/gtwizard_0_example_bit_synchronizer.v" \
"../ref/gtwizard/sim/gtwizard_0_example_gtwiz_userclk_rx.v" \
"../ref/gtwizard/sim/gtwizard_0_example_gtwiz_userclk_tx.v" \
"../ref/gtwizard/sim/gtwizard_0_example_reset_synchronizer.v" \
"../ref/gtwizard/sim/gtwizard_0_prbs_any.v" \
"../ref/gtwizard/sim/gtwizard_0_example_checking_64b66b_async.v" \
"../ref/gtwizard/sim/gtwizard_0_example_init.v" \
"../ref/gtwizard/sim/gtwizard_0_example_stimulus_64b66b_async.v" \
"../ref/gtwizard/sim/gtwizard_0_example_wrapper.v" \

#mac
vlog +incdir+../ref/mac/xge_ll_mac/trunk/rtl -work xil_defaultlib ../ref/mac/xge_ll_mac/trunk/rtl/oc_mac.v
vlog +incdir+../ref/mac/xge_ll_mac/trunk/rtl -work xil_defaultlib ../ref/mac/xge_ll_mac/trunk/rtl/rx_control.v
vlog +incdir+../ref/mac/xge_ll_mac/trunk/rtl -work xil_defaultlib ../ref/mac/xge_ll_mac/trunk/rtl/rx_enqueue.v
vlog +incdir+../ref/mac/xge_ll_mac/trunk/rtl -work xil_defaultlib ../ref/mac/xge_ll_mac/trunk/rtl/tx_control.v
vlog +incdir+../ref/mac/xge_ll_mac/trunk/rtl -work xil_defaultlib ../ref/mac/xge_ll_mac/trunk/rtl/tx_dequeue.v

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L gtwizard_ultrascale_v1_6_3 -L xil_defaultlib -lib xil_defaultlib tb_single_loopback xil_defaultlib.glbl

do {wave.do}

log -r *
view wave
view structure
view signals

run 20us
