######################################################################
#
# File name : gtwizard_0_TB_compile.do
# Created on: Mon Mar 11 22:12:59 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vmap work work

vlog -work work ../rtl/phy/single_lane_gt.v
vlog -work work ../rtl/phy/multi_lane_gt.v
vlog -work work ../rtl/phy/multi_lane_init.v
vlog -work work ../rtl/phy/sync_block.v
vlog -work work ../rtl/phy/sync_pulse.v
vlog -work work ../rtl/phy/rx_manual_phase_align.v
vlog -work work ../rtl/phy/rx_startup_fsm.v
vlog -work work ../rtl/phy/tx_manual_phase_align.v
vlog -work work ../rtl/phy/tx_startup_fsm.v
vlog -work work ../rtl/phy/gt_common.v
vlog -work work ../rtl/phy/gt_common_reset.v
vlog -work work ../rtl/phy/gt_usr_clk_source.v
vlog -work work ../rtl/phy/gt_clock_module.v
vlog -work work ../rtl/phy/teng_phy.v
vlog -work work ../rtl/phy/loopback.v
vlog -work work +incdir+../rtl/include ../rtl/mac/teng_mac.v
vlog -work work +incdir+../rtl/include ../rtl/mac/decode_64b_66b.v
vlog -work work +incdir+../rtl/include ../rtl/mac/descramble.v
vlog -work work +incdir+../rtl/include ../rtl/mac/encode_64b_66b.v
vlog -work work +incdir+../rtl/include ../rtl/mac/scramble.v
vlog -work work +incdir+../rtl/include ../rtl/mac/rx_alignment.v
vlog -work work +incdir+../rtl/include ../rtl/mac/axis2xgmii32.v
vlog -work work +incdir+../rtl/include ../rtl/mac/xgmii2axis32.v
vlog -work work +incdir+../rtl/include ../rtl/mac/rx.v
vlog -work work +incdir+../rtl/include ../rtl/mac/tx.v
vlog -work work +incdir+../rtl/include ../rtl/mac/gearbox_64b_66b.v
vlog -work work +incdir+../rtl/include ../rtl/mac/gearbox_66b_64b.v
vlog -work work +incdir+../rtl/include ../rtl/mac/prbs_gen.v
vlog -work work +incdir+../rtl/include ../rtl/mac/prbs_check.v
vlog -work work +incdir+../rtl/include ../rtl/mac/prbs_test.v
vlog -work work +incdir+../rtl/include ../rtl/mac/prbs_any.v
vlog -work work +incdir+../rtl/include ../rtl/xm_top.v


vlog -sv -work work ./sim_stream_master.sv
vlog -sv -work work ./tb_prbs_loopback.sv

# compile glbl module
vlog -work work "glbl.v"

vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib work work.tb_prbs_loopback work.glbl

do wave.do

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

view wave
view structure
view signals

run 1000ns
