onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/ref_clk_n_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/ref_clk_p_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/gt_rxn_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/gt_rxp_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/gt_txn_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/gt_txp_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/sys_clk_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/sys_reset_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/link_up_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_user_clk_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_user_rst_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_data_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_vldb_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_valid_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_ready_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_last_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_user_i
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_status_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/tx_rsp_valid_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_user_clk_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_user_rst_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_data_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_vldb_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_valid_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_last_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/rx_user_o
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/s_rx_fsm_reset_done
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/s_tx_fsm_reset_done
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/s_link_up
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/s_gt_rx_data
add wave -noupdate -group xm_top /tb_prbs_loopback/u_prbs_test/u_xm_top/s_gt_tx_data
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/sys_clk_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/soft_reset_tx_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/soft_reset_rx_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/gt_ref_clk_pad_n_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/gt_ref_clk_pad_p_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/dont_reset_on_data_error_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/data_valid_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/rx_user_clk_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/rx_fsm_reset_done_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/rx_data_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/gtx_rxp_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/gtx_rxn_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/tx_user_clk_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/tx_fsm_reset_done_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/tx_data_i
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/gtx_txp_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/gtx_txn_o
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_usr_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_usr_clk2
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_out_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_clk_lock
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_mmcm_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_rx_usr_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_rx_usr_clk2
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_rx_out_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_qpll_lock
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_qpll_ref_clk_lost
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_gt_qpll_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_qpll_out_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_qpll_out_ref_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_common_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_rx_pcs_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_rx_pma_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_pcs_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tx_pma_reset
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tied_to_ground
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tied_to_ground_vec64
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tied_to_vcc
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_tied_to_vcc_vec8
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_gt_ref_clk
add wave -noupdate -group teng_phy /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/s_qpll_reset
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tx_usr_clk_o
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tx_usr_clk2_o
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tx_out_clk_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tx_clk_lock_o
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tx_mmcm_reset_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/rx_usr_clk_o
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/rx_usr_clk2_o
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/rx_out_clk_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/gt_ref_clk_pad_n_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/gt_ref_clk_pad_p_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/gt_ref_clk_o
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tied_to_ground_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/tied_to_vcc_i
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/s_gt_ref_clk_buf
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/s_rx_usr_clk_buf
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/s_tx_usr_clk_buf
add wave -noupdate -group gt_usr_clk_source /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_gt_usr_clk_source/s_tx_out_clk_mmcm_locked
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_ref_clk_sel_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/gt_ref_clk0_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/gt_ref_clk1_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_lock_o
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_lock_det_clk_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_out_clk_o
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_out_ref_clk_o
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_ref_clk_lost_o
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/qpll_reset_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/tied_to_ground_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/tied_to_ground_vec_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/tied_to_vcc_i
add wave -noupdate -group common /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common/tied_to_vcc_vec_i
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/stable_clk_i
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/soft_reset_i
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/common_reset_o
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/init_wait_count
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/init_wait_done
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/common_reset_i
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/common_reset_asserted
add wave -noupdate -group common_reset /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_common_reset/state
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/sys_clk_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/soft_reset_tx_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/soft_reset_rx_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/dont_reset_on_data_error_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/tx_fsm_reset_done_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rx_fsm_reset_done_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/data_valid_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/tx_mmcm_lock_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/tx_mmcm_reset_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drpaddr_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drpclk_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drpdi_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drpdo_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drpen_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drprdy_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/drpwe_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/dmonitorout_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/loopback_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxrate_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/eyescanreset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/eyescandataerror_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/eyescantrigger_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxcdrhold_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxusrclk_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxusrclk2_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txdata_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxdata_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/gtxrxp_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/gtxrxn_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxbufreset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxbufstatus_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxphmonitor_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxphslipmonitor_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxdfelpmreset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxmonitorout_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxmonitorsel_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxratedone_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxoutclk_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxoutclkfabric_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxpcsreset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxpmareset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxlpmen_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/rxpolarity_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txpostcursor_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txprecursor_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txusrclk_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txusrclk2_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txbufstatus_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txdiffctrl_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txinhibit_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txmaincursor_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txdata_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/gtxtxn_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/gtxtxp_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txoutclk_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txoutclkfabric_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txoutclkpcs_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txpcsreset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txpmareset_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/txpolarity_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/qplllock_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/qpllrefclklost_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/qpllreset_o
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/qplloutclk_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/qplloutrefclk_i
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_reset_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_reset_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_gt_tx_reset
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_gt_rx_reset
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_user_rdy
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_user_rdy
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_dfe_agc_hold
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_dfe_lf_hold
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_lpm_lf_hold
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_lpm_hf_hold
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_qpll_reset
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tied_to_ground
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tied_to_vcc
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_run_tx_phalignment
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rst_tx_phalignment
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_phalignment_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_run_rx_phalignment
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rst_rx_phalignment
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_phalignment_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_dly_sreset
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_dly_sreset_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_ph_init
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_ph_init_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_ph_align
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_ph_align_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_dly_en
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_ph_align_en
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_tx_ph_dly_reset
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_dly_sreset
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_dly_sreset_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_ph_align
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_ph_align_done
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_dly_en
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_ph_align_en
add wave -noupdate -group multi_lane_init /tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/s_rx_ph_dly_reset
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_user_clk_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_fsm_reset_done_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_data_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_user_clk_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_fsm_reset_done_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_data_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/link_up_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_user_rst_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_data_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_vldb_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_valid_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_ready_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_last_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_user_i
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_status_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_rsp_valid_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_user_rst_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_data_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_vldb_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_valid_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_last_o
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/rx_user_o
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_gt_rx_data}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_gb_rx_data}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_gb_rx_head}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_gb_rx_head_valid}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_rx_data}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_rx_head}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_rx_head_valid}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_rx_gearbox_slip}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_tx_data}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_tx_header}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_tx_sequence}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/s_gb_data_out}
add wave -noupdate -group mac {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/rx_user_clk_o}
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/r_tx_fsm_reset_done_d
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/r_tx_fsm_reset_done_d2
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/r_rx_fsm_reset_done_d
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/r_rx_fsm_reset_done_d2
add wave -noupdate -group mac /tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/tx_user_clk_o
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/stable_clk_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_user_clk_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/soft_reset_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/qpll_ref_clk_lost_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/cpll_ref_clk_lost_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/qpll_lock_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/cpll_lock_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_reset_done_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/mmcm_lock_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/gt_tx_reset_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/mmcm_reset_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/qpll_reset_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/cpll_reset_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_fsm_reset_done_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_user_rdy_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/run_phalignment_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/reset_phalignment_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/phalignment_done_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/retry_count_o}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_state}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/init_wait_count}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/init_wait_done}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/pll_reset_asserted}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_fsm_reset_done_int}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_fsm_reset_done_int_s2}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/tx_fsm_reset_done_int_s3}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/retry_counter_int}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_out_counter}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/reset_time_out}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_out_2ms}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_tlock_max}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_out_500us}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/mmcm_lock_count}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/mmcm_lock_int}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/s_mmcm_lock}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/mmcm_lock_reclocked}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/run_phase_alignment_int}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/run_phase_alignment_int_s2}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/run_phase_alignment_int_s3}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/wait_bypass_count}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_out_wait_bypass}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_out_wait_bypass_s2}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/time_out_wait_bypass_s3}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/txresetdone_s2}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/txresetdone_s3}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/gttxreset_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/txpmaresetdone_i}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/txpmaresetdone_sync}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/refclk_lost}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/cplllock_sync}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/qplllock_sync}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/wait_time_cnt}
add wave -noupdate -group tx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_tx_startup_fsm/wait_time_done}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/stable_clk_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_user_clk_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/soft_reset_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/qpll_ref_clk_lost_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/cpll_ref_clk_lost_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/qpll_lock_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/cpll_lock_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_reset_done_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/mmcm_lock_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rec_clk_stable_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rec_clk_monitor_restart_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/data_valid_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/tx_user_rdy_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/dont_reset_on_data_error_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/gt_rx_reset_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/mmcm_reset_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/qpll_reset_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/cpll_reset_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_fsm_reset_done_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_user_rdy_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/run_phalignment_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/phalignment_done_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/reset_phalignment_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_dfe_agc_hold_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_dfe_lf_hold_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_lpm_lf_hold_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_lpm_hf_hold_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/retry_count_o}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_state}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/init_wait_count}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/init_wait_done}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/pll_reset_asserted}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_fsm_reset_done_int}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_fsm_reset_done_int_s2}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rx_fsm_reset_done_int_s3}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/retry_counter_int}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_counter}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/recclk_mon_restart_count}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/recclk_mon_count_reset}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/reset_time_out}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_2ms}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_tlock_max}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_500us}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_1us}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_100us}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/check_tlock_max}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/mmcm_lock_count}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/mmcm_lock_int}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/s_mmcm_lock}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/mmcm_lock_reclocked}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/run_phase_alignment_int}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/run_phase_alignment_int_s2}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/run_phase_alignment_int_s3}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/txpmaresetdone_s}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/reset_stage1}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/reset_stage1_tx}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/gtrxreset_s}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/gtrxreset_tx_s}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/wait_bypass_count}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_wait_bypass}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_wait_bypass_s2}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_wait_bypass_s3}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/r_gt_rx_reset}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/r_mmcm_reset}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxpmaresetdone_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/txpmaresetdone_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/refclk_lost}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxpmaresetdone_sync}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/txpmaresetdone_sync}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxpmaresetdone_s}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxpmaresetdone_ss}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxpmaresetdone_rx_s}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/pmaresetdone_fallingedge_detect}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/pmaresetdone_fallingedge_detect_s}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxresetdone_s2}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/rxresetdone_s3}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/data_valid_sync}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/gtrxreset_tx_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/gtrxreset_rx_i}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/cplllock_sync}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/qplllock_sync}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/cplllock_ris_edge}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/qplllock_ris_edge}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/cplllock_prev}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/qplllock_prev}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/adapt_count}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/time_out_adapt}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/adapt_count_reset}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/wait_time_cnt}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/wait_time_done}
add wave -noupdate -group rx_startup_fsm {/tb_prbs_loopback/u_prbs_test/u_xm_top/g_gt_on/u_teng_phy/u_multi_lane_init/g_init[0]/u_rx_startup_fsm/PHALIGNMENT_DONE_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/clk_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/rst_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/data_o}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/head_o}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/sequence_o}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tdata_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tvldb_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tvalid_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tready_o}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tlast_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tuser_i}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tx_status_o}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/tx_rsp_valid_o}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_xgmii_d}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_xgmii_c}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_xgmii_d}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_xgmii_c}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_xgmii_txd_64}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_xgmii_txc_64}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_xgmii_txd_vld_64}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_encode_data}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_encode_head}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_encode_data_vld}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_encode_error}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_tx_scrambled_data}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_tx_scrambled_head}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_tx_scrambled_valid}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/s_sequence}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_sequence_d1}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_sequence_d2}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_sequence_d3}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_sequence_d4}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_sequence_d5}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_data}
add wave -noupdate -group mac_tx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_tx/r_head}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/clk_i}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/rst_i}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/data_i}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/head_i}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/head_valid_i}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/slip_o}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/tdata_o}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/tvldb_o}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/tvalid_o}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/tlast_o}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/tuser_o}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_rx_lane_locked}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_data}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_head}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_rx_descrambled_data}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_rx_descrambled_head}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_rx_descrambled_data_rev}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_rx_descrambled_head_rev}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_rx_descrambled_valid}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_decode_data}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_decode_head}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_decode_data_vld}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_decode_error}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_xgmii_rxd_64}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_xgmii_rxc_64}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/s_xgmii_rxd_vld_64}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_xgmii_rxd_vld_64}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_xgmii_d_32}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_xgmii_c_32}
add wave -noupdate -group mac_rx {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/r_xgmii_v_32}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/clk_i}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/rst_i}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/data_o}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/head_o}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/head_valid_o}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/slip_i}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/data_i}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_count}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_sft_count}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_sft_count2}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_sft_init}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_see_slip}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_slip}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_data}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/r_storage}
add wave -noupdate -group gearbox_64_66 {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_gearbox_64_66/s_aligned_data_in}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/clk_i}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/rst_i}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/gtwiz_userdata_rx_i}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/rxheader_i}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/rxheadervalid_i}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/rxgearboxslip_o}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/locked}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/r_aligned_count}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/r_rxgearboxslip}
add wave -noupdate -group rx_alignment {/tb_prbs_loopback/u_prbs_test/u_xm_top/u_teng_mac/g_mac[0]/u_rx/u_rx_alignment/r_sleep}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {69979522 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 215
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {105 us}
