######################################################################
#
# File name : ten_gig_eth_mac_0_demo_tb_compile.do
# Created on: Tue Jan 22 11:40:25 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work

vmap work work

vlog -64 -incr -work work  \
"../rtl/ten_gig_eth_mac_0_core.v" \
"../rtl/ten_gig_eth_mac_0_block.v" \
"../rtl/ten_gig_eth_mac_0.v" \

vlog -64 -incr -sv -work work ../../gth_no_buffer_with_gearbox/sim/sim_stream_master.sv
vlog -64 -incr -sv -work work ./top.sv
# compile glbl module
vlog -work work "glbl.v"

vsim -voptargs="+acc" -L ten_gig_eth_mac_v15_1_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib work work.top work.glbl

log -r *
run 10us