######################################################################
#
# File name : gtwizard_ultrascale_0_example_top_sim_compile.do
# Created on: Mon Jan 21 11:05:07 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../ref/gtwizard/imports" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_v1_7_gthe3_channel.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gthe3_channel_wrapper.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_v1_7_gthe3_common.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gthe3_common_wrapper.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gtwizard_gthe3.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_gtwizard_top.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0.v" \
"../ref/gtwizard/srcs/gtwizard_ultrascale_0_vio_0.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_bit_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_checking_64b66b.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_rx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_tx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_init.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_reset_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_stimulus_64b66b.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_top.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_wrapper.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_prbs_any.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_0_example_top_sim.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

vsim -voptargs="+acc" -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.gtwizard_ultrascale_0_example_top_sim xil_defaultlib.glbl 