
vlib sim_nphy
vmap sim_nphy sim_nphy

vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/altera_xcvr_functions.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/altera_xcvr_functions.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_pcs.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_pcs_ch.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_pma.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_reconfig_bundle_to_xcvr.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_reconfig_bundle_to_ip.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_reconfig_bundle_merger.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_rx_pma.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_tx_pma.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_tx_pma_ch.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_h.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_avmm_csr.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_avmm_dcd.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_avmm.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_data_adapter.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_native.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_xcvr_plls.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_pcs.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_pcs_ch.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_pma.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_reconfig_bundle_to_xcvr.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_reconfig_bundle_to_ip.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_reconfig_bundle_merger.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_rx_pma.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_tx_pma.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_tx_pma_ch.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_h.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_avmm_csr.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_avmm_dcd.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_avmm.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_data_adapter.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_native.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_xcvr_plls.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/alt_xcvr_resync.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/alt_xcvr_resync.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_10g_rx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_10g_tx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_8g_rx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_8g_tx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_8g_pcs_aggregate_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_common_pcs_pma_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_common_pld_pcs_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_pipe_gen1_2_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_pipe_gen3_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_rx_pcs_pma_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_rx_pld_pcs_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_tx_pcs_pma_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/sv_hssi_tx_pld_pcs_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_10g_rx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_10g_tx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_8g_rx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_8g_tx_pcs_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_8g_pcs_aggregate_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_common_pcs_pma_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_common_pld_pcs_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_pipe_gen1_2_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_pipe_gen3_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_rx_pcs_pma_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_rx_pld_pcs_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_tx_pcs_pma_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/sv_hssi_tx_pld_pcs_interface_rbc.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/altera_xcvr_native_sv_functions_h.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/altera_xcvr_native_sv.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/altera_xcvr_native_sv_functions_h.sv
vlog -sv -work sim_nphy ../rtl/altera_phy/ip/nphy/nphy_sim/altera_xcvr_native_sv/mentor/altera_xcvr_native_sv.sv

vlib sim_xcvr_reconfig
vmap sim_xcvr_reconfig sim_xcvr_reconfig
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_xcvr_functions.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/altera_xcvr_functions.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_h.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_h.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_resync.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_resync.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_h.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_h.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_dfe_cal_sweep_h.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_dfe_cal_sweep_h.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cal_seq.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_cal_seq.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xreconf_cif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xreconf_cif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xreconf_uif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xreconf_uif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xreconf_basic_acq.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xreconf_basic_acq.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_analog.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_analog.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_analog_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_analog_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xreconf_analog_datactrl.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xreconf_analog_datactrl.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xreconf_analog_rmw.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xreconf_analog_rmw.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xreconf_analog_ctrlsm.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xreconf_analog_ctrlsm.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_offset_cancellation.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_offset_cancellation.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_offset_cancellation_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_offset_cancellation_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_eyemon.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_eyemon.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_eyemon_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_eyemon_ctrl_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_eyemon_ber_sv.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/ber_reader_dcfifo.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/step_to_mon_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mon_to_step_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_eyemon_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_eyemon_ctrl_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_eyemon_ber_sv.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/ber_reader_dcfifo.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/step_to_mon_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/mon_to_step_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_reg_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_cal_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_cal_sweep_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_cal_sweep_datapath_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_oc_cal_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_pi_phase_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_step_to_mon_en_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_adapt_tap_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_ctrl_mux_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_local_reset_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_cal_sim_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dfe_adapt_tap_sim_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_reg_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_cal_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_cal_sweep_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_cal_sweep_datapath_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_oc_cal_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_pi_phase_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_step_to_mon_en_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_adapt_tap_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_ctrl_mux_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_local_reset_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_cal_sim_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dfe_adapt_tap_sim_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_adce.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_adce.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_adce_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_adce_datactrl_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_adce_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_adce_datactrl_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_cal.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_control.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_datapath.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_pll_reset.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_eye_width.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_align_clk.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_get_sum.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_dcd_cal_sim_model.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_sv.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_cal.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_control.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_datapath.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_pll_reset.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_eye_width.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_align_clk.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_get_sum.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_dcd_cal_sim_model.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_mif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_mif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_reconfig_mif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_reconfig_mif_ctrl.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_reconfig_mif_avmm.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_reconfig_mif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_reconfig_mif_ctrl.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_reconfig_mif_avmm.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_pll.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_pll.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_reconfig_pll.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_reconfig_pll_ctrl.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_reconfig_pll.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_reconfig_pll_ctrl.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_soc.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_ram.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_direct.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xrbasic_l2p_addr.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xrbasic_l2p_ch.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xrbasic_l2p_rom.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xrbasic_lif_csr.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xrbasic_lif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_xcvr_reconfig_basic.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_arbiter_acq.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_basic.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xrbasic_l2p_addr.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xrbasic_l2p_ch.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xrbasic_l2p_rom.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xrbasic_lif_csr.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xrbasic_lif.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_xcvr_reconfig_basic.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_arbiter_acq.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_reconfig_basic.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_arbiter.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_m2s.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_wait_generate.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_csr_selector.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_arbiter.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_m2s.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/altera_wait_generate.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/alt_xcvr_csr_selector.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/sv_reconfig_bundle_to_basic.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/mentor/sv_reconfig_bundle_to_basic.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu.v"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_reconfig_cpu.v"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_reconfig_cpu_test_bench.v"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_irq_mapper.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_reset_controller.v"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_reset_synchronizer.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_merlin_master_translator.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_merlin_slave_translator.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_merlin_master_agent.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_merlin_slave_agent.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_merlin_burst_uncompressor.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_avalon_sc_fifo.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_router.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_router_001.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_router_002.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_router_003.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_cmd_demux.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_cmd_demux_001.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_cmd_mux.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/altera_merlin_arbitrator.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_cmd_mux_001.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_rsp_mux.sv"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_rsp_mux_001.sv"
vlog      -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_avalon_st_adapter.v"
vlog -sv  -work sim_xcvr_reconfig "../rtl/altera_phy/ip/xcvr_reconfig//xcvr_reconfig_sim/alt_xcvr_reconfig/alt_xcvr_reconfig_cpu_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv"

vlib sim_xcvr_reset
vmap sim_xcvr_reset sim_xcvr_reset
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/altera_xcvr_functions.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/mentor/altera_xcvr_functions.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/alt_xcvr_resync.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/mentor/alt_xcvr_resync.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/altera_xcvr_reset_control.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/alt_xcvr_reset_counter.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/mentor/altera_xcvr_reset_control.sv"
vlog -sv -work sim_xcvr_reset  "../rtl/altera_phy/ip/xcvr_reset/xcvr_reset_sim/altera_xcvr_reset_control/mentor/alt_xcvr_reset_counter.sv"