######################################################################
#
# File name : gtwizard_ultrascale_1_example_top_sim_compile.do
# Created on: Tue Feb 19 20:03:01 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/gtwizard_ultrascale_v1_7_3
vlib modelsim_lib/msim/xil_defaultlib

vmap gtwizard_ultrascale_v1_7_3 modelsim_lib/msim/gtwizard_ultrascale_v1_7_3
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work gtwizard_ultrascale_v1_7_3  "+incdir+../ref/imports" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
"../ref/gtwizard/ipstatic/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../ref/imports" \
"../ref/gtwizard/sim/gtwizard_ultrascale_v1_7_gthe3_channel.v" \
"../ref/gtwizard/sim/gtwizard_ultrascale_1_gthe3_channel_wrapper.v" \
"../ref/gtwizard/sim/gtwizard_ultrascale_1_gtwizard_gthe3.v" \
"../ref/gtwizard/sim/gtwizard_ultrascale_1_gtwizard_top.v" \
"../ref/gtwizard/sim/gtwizard_ultrascale_1.v" \
"../ref/gtwizard/sim/gtwizard_ultrascale_1_vio_0.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_bit_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_checking_raw.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_buffbypass_rx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_buffbypass_tx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_reset.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_userclk_rx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_userclk_tx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_userdata_rx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_gtwiz_userdata_tx.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_init.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_reset_inv_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_reset_sync.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_stimulus_raw.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_top.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_wrapper.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_gthe3_common_wrapper.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_prbs_any.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_v1_7_gthe3_common.v" \
"../ref/gtwizard/imports/gtwizard_ultrascale_1_example_top_sim.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

vsim -voptargs="+acc" -L gtwizard_ultrascale_v1_7_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.gtwizard_ultrascale_1_example_top_sim xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {wave.do}

view wave
view structure
view signals


run -all

